title: Elias Bou Faycal # your name (or website title) here
logo: "/images/Elias Pic.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Driven Underwriter
  <br><br>
  <a href="https://www.linkedin.com/in/eliasbf/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
